# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port if needed (fastmcp could be using stdio though default configuration uses stdio, so optional)
# EXPOSE 8000

# Command to run the MCP server
CMD ["python", "server.py"]
